Update CWODMR notebook with a working example.
qt3uw/qt3-utils pull request #97
Opened 2023-03-29 21:13 UTC by ws-general

Working ODMR example as of 3/29/2023.

2023-03-29 21:24 UTC, gadamc requested changes
Overall, this looks great. But if you have time, some explanatory text would be nice.

2023-03-29 21:43 UTC, gadamc commented on examples/default_cwodmr.ipynb
Also, we should remove the cell with `%matplotlib notebook` because that's specific for notebook users, not necessary to demonstrate the usage, and might not work in Jupyter Lab.

2023-03-29 21:52 UTC, ws-general commented on examples/default_cwodmr.ipynb
Mardown has been added.

2023-03-30 01:29 UTC, gadamc commented on examples/default_cwodmr.ipynb
@ws-general I've added some text that explains a lot of details. If you don't mind, could you read through and tell me if it makes sense to you and if there's anything that is confusing or where I use jargon that is not understood. Thanks.

2023-03-31 21:36 UTC, gadamc requested changes

2023-03-31 21:36 UTC, gadamc commented on examples/default_cwodmr.ipynb
After a self-review, I only see there could me a line of text before the nidaq configuration object is created which explains the purpose of the object.

2023-03-31 21:41 UTC, ws-general reviewed
The changes look great to me!

2023-04-02 22:42 UTC, gadamc approved these changes

2023-04-03 00:26 UTC, merged